paths:
  /api/products:
    get:
      summary: Obtenemos todos los productos de la BD
      tags:
        - Products
      responses:
        "200":
          description: Productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor
    post:
      summary: Este endpoint crea un producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado correctamente
  /api/products/{pid}:
    get:
      summary: Obtiene un solo producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se quiere buscar
          schema:
            type: string
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor
    put:
      summary: Actualizamos producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se quiere actualizar
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto actualizado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor
    delete:
      summary: Eliminamos producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que se quiere eliminar
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado correctamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error interno del servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID autogenerado por MongoDB
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnails:
          type: string
          description: URL de la imagen del producto
        stock:
          type: number
          description: Stock disponible del producto
        code:
          type: string
          description: Código único del producto
        status:
          type: boolean
          description: Estado del producto
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario del producto
      example:
        _id: "60d5ec49e1378b001c8d4c7e"
        title: "Cable HDMI"
        description: "Cable HDMI de alta velocidad"
        price: 25.99
        thumbnails: "https://example.com/imagen.jpg"
        stock: 50
        code: "HDMI-001"
        status: true
        category: "Cables"
        owner: "admin"
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnails:
          type: string
          description: URL de la imagen del producto
        stock:
          type: number
          description: Stock disponible del producto
        code:
          type: string
          description: Código único del producto
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario del producto
      example:
        title: "Cable HDMI"
        description: "Cable HDMI de alta velocidad"
        price: 25.99
        thumbnails: "https://example.com/imagen.jpg"
        stock: 50
        code: "HDMI-001"
        category: "Cables"
        owner: "admin"
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Título del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        thumbnails:
          type: string
          description: URL de la imagen del producto
        stock:
          type: number
          description: Stock disponible del producto
        code:
          type: string
          description: Código único del producto
        category:
          type: string
          description: Categoría del producto
        owner:
          type: string
          description: Propietario del producto
      example:
        title: "Cable HDMI"
        description: "Cable HDMI de alta velocidad"
        price: 25.99
        thumbnails: "https://example.com/imagen.jpg"
        stock: 50
        code: "HDMI-001"
        category: "Cables"
        owner: "admin"